[package]
name = "cumulus-pallet-dmp-queue"
version = "0.4.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "cumulus-pallet-dmp-queue"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", features = [ "derive" ], default-features = false }
log = { version = "0.4.20", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

# Substrate
frame-support = { path = "../../../substrate/frame/support", default-features = false, version = "25.0.0" }
frame-system = { path = "../../../substrate/frame/system", default-features = false, version = "25.0.0" }
sp-io = { path = "../../../substrate/primitives/io", default-features = false, version = "27.0.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, version = "28.0.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "12.0.0" }

# Polkadot
xcm = { package = "staging-xcm", path = "../../../polkadot/xcm", default-features = false, version = "4.0.0" }

# Cumulus
cumulus-primitives-core = { path = "../../primitives/core", default-features = false, version = "0.4.0" }

[dev-dependencies]
sp-core = { path = "../../../substrate/primitives/core", default-features = false }
sp-version = { path = "../../../substrate/primitives/version", default-features = false }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"cumulus-primitives-core/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"scale-info/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
