[package]
name = "sc-basic-authorship"
version = "0.31.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Basic implementation of block-authoring logic."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
futures = "0.3.21"
futures-timer = "3.0.1"
log = "0.4.17"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../utils/prometheus", version = "0.16.0" }
sc-block-builder = { version = "0.30.0", path = "../block-builder" }
sc-client-api = { version = "25.0.0", path = "../api" }
sc-proposer-metrics = { version = "0.16.0", path = "../proposer-metrics" }
sc-telemetry = { version = "12.0.0", path = "../telemetry" }
sc-transaction-pool-api = { version = "25.0.0", path = "../transaction-pool/api" }
sp-api = { version = "23.0.0", path = "../../primitives/api" }
sp-blockchain = { version = "25.0.0", path = "../../primitives/blockchain" }
sp-consensus = { version = "0.29.0", path = "../../primitives/consensus/common" }
sp-core = { version = "25.0.0", path = "../../primitives/core" }
sp-inherents = { version = "23.0.0", path = "../../primitives/inherents" }
sp-runtime = { version = "28.0.0", path = "../../primitives/runtime" }

[dev-dependencies]
parking_lot = "0.12.1"
sc-transaction-pool = { path = "../transaction-pool" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }
