[package]
name = "polkadot-availability-recovery"
version = "4.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-availability-recovery"

[dependencies]
futures = "0.3.21"
schnellru = "0.2.1"
rand = "0.8.5"
fatality = "0.0.6"
thiserror = "1.0.48"
async-trait = "0.1.73"
gum = { package = "tracing-gum", path = "../../gum", version = "4.0.0" }
polkadot-erasure-coding = { version = "4.0.0", path = "../../../erasure-coding" }
polkadot-primitives = { version = "4.0.0", path = "../../../primitives" }
polkadot-node-primitives = { version = "4.0.0", path = "../../primitives" }
polkadot-node-subsystem = { version = "4.0.0", path = "../../subsystem" }
polkadot-node-subsystem-util = { version = "4.0.0", path = "../../subsystem-util" }
polkadot-node-network-protocol = { version = "4.0.0", path = "../protocol" }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
sc-network = { version = "0.31.0", path = "../../../../substrate/client/network" }

[dev-dependencies]
assert_matches = "1.4.0"
env_logger = "0.9.0"
futures-timer = "3.0.2"
log = "0.4.17"
sp-core = { path = "../../../../substrate/primitives/core" }
sp-keyring = { path = "../../../../substrate/primitives/keyring" }
sp-application-crypto = { path = "../../../../substrate/primitives/application-crypto" }
sc-network = { path = "../../../../substrate/client/network" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
