[package]
name = "sc-sync-state-rpc"
version = "0.31.0"
authors.workspace = true
description = "A RPC handler to create sync states for light clients."
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.48"
sc-chain-spec = { version = "24.0.0", path = "../chain-spec" }
sc-client-api = { version = "25.0.0", path = "../api" }
sc-consensus-babe = { version = "0.31.0", path = "../consensus/babe" }
sc-consensus-epochs = { version = "0.30.0", path = "../consensus/epochs" }
sc-consensus-grandpa = { version = "0.16.0", path = "../consensus/grandpa" }
sp-blockchain = { version = "25.0.0", path = "../../primitives/blockchain" }
sp-runtime = { version = "28.0.0", path = "../../primitives/runtime" }
