[package]
name = "cumulus-primitives-parachain-inherent"
version = "0.4.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "cumulus-primitives-parachain-inherent"

[dependencies]
async-trait = { version = "0.1.73", optional = true }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [ "derive" ] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
tracing = { version = "0.1.37", optional = true }

# Substrate
sc-client-api = { path = "../../../substrate/client/api", optional = true, version = "25.0.0" }
sp-api = { path = "../../../substrate/primitives/api", optional = true, version = "23.0.0" }
sp-core = { path = "../../../substrate/primitives/core", default-features = false, version = "25.0.0" }
sp-inherents = { path = "../../../substrate/primitives/inherents", default-features = false, version = "23.0.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", optional = true, version = "28.0.0" }
sp-state-machine = { path = "../../../substrate/primitives/state-machine", optional = true, version = "0.32.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "12.0.0" }
sp-storage = { path = "../../../substrate/primitives/storage", optional = true, version = "17.0.0" }
sp-trie = { path = "../../../substrate/primitives/trie", default-features = false, version = "26.0.0" }

# Cumulus
cumulus-primitives-core = { path = "../core", default-features = false, version = "0.4.0" }
cumulus-relay-chain-interface = { path = "../../client/relay-chain-interface", optional = true, version = "0.4.0" }
cumulus-test-relay-sproof-builder = { path = "../../test/relay-sproof-builder", optional = true, version = "0.4.0" }

[features]
default = [ "std" ]
std = [
	"async-trait",
	"codec/std",
	"cumulus-primitives-core/std",
	"cumulus-relay-chain-interface",
	"cumulus-test-relay-sproof-builder",
	"sc-client-api",
	"scale-info/std",
	"sp-api",
	"sp-core/std",
	"sp-inherents/std",
	"sp-runtime",
	"sp-state-machine",
	"sp-std/std",
	"sp-storage",
	"sp-trie/std",
	"tracing",
]
