[package]
name = "sc-rpc-api"
version = "0.30.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate RPC interfaces."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0"
sc-chain-spec = { version = "24.0.0", path = "../chain-spec" }
sc-mixnet = { version = "0.1.0", path = "../mixnet" }
sc-transaction-pool-api = { version = "25.0.0", path = "../transaction-pool/api" }
sp-core = { version = "25.0.0", path = "../../primitives/core" }
sp-rpc = { version = "23.0.0", path = "../../primitives/rpc" }
sp-runtime = { version = "28.0.0", path = "../../primitives/runtime" }
sp-version = { version = "26.0.0", path = "../../primitives/version" }
jsonrpsee = { version = "0.16.2", features = ["server", "client-core", "macros"] }
