[package]
name = "try-runtime-cli"
version = "0.35.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Cli command runtime testing and dry-running"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
remote-externalities = { package = "frame-remote-externalities", path = "../../remote-externalities", version = "0.32.0" }
sc-cli = { version = "0.33.0", path = "../../../../client/cli" }
sc-executor = { version = "0.29.0", path = "../../../../client/executor" }
sp-consensus-aura = { version = "0.29.0", path = "../../../../primitives/consensus/aura" }
sp-consensus-babe = { version = "0.29.0", path = "../../../../primitives/consensus/babe" }
sp-core = { version = "25.0.0", path = "../../../../primitives/core" }
sp-externalities = { version = "0.23.0", path = "../../../../primitives/externalities" }
sp-inherents = { version = "23.0.0", path = "../../../../primitives/inherents" }
sp-io = { version = "27.0.0", path = "../../../../primitives/io" }
sp-keystore = { version = "0.31.0", path = "../../../../primitives/keystore" }
sp-runtime = { version = "28.0.0", path = "../../../../primitives/runtime" }
sp-rpc = { version = "23.0.0", path = "../../../../primitives/rpc" }
sp-state-machine = { version = "0.32.0", path = "../../../../primitives/state-machine" }
sp-timestamp = { version = "23.0.0", path = "../../../../primitives/timestamp" }
sp-transaction-storage-proof = { version = "23.0.0", path = "../../../../primitives/transaction-storage-proof" }
sp-version = { version = "26.0.0", path = "../../../../primitives/version" }
sp-debug-derive = { version = "12.0.0", path = "../../../../primitives/debug-derive" }
sp-api = { version = "23.0.0", path = "../../../../primitives/api" }
sp-weights = { version = "24.0.0", path = "../../../../primitives/weights" }
frame-try-runtime = { path = "../../../../frame/try-runtime", optional = true, version = "0.31.0" }
substrate-rpc-client = { version = "0.30.0", path = "../../rpc/client" }

async-trait = "0.1.57"
clap = { version = "4.4.6", features = ["derive"] }
hex = { version = "0.4.3", default-features = false }
log = "0.4.17"
parity-scale-codec = "3.6.1"
serde = "1.0.188"
serde_json = "1.0.107"
zstd = { version = "0.12.4", default-features = false }

[dev-dependencies]
assert_cmd = "2.0.10"
node-primitives = { path = "../../../../bin/node/primitives" }
regex = "1.7.3"
substrate-cli-test-utils = { path = "../../../../test-utils/cli" }
tempfile = "3.1.0"
tokio = "1.27.0"

[features]
try-runtime = [
	"frame-try-runtime/try-runtime",
	"sp-debug-derive/force-debug",
	"sp-runtime/try-runtime",
]
