[package]
name = "cumulus-client-cli"
version = "0.4.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "cumulus-client-cli"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.0.0" }
url = "2.4.0"
sc-cli = { version = "0.33.0", path = "../../../substrate/client/cli" }
sc-client-api = { version = "25.0.0", path = "../../../substrate/client/api" }
sc-chain-spec = { version = "24.0.0", path = "../../../substrate/client/chain-spec" }
sc-service = { version = "0.32.0", path = "../../../substrate/client/service" }
sp-core = { version = "25.0.0", path = "../../../substrate/primitives/core" }
sp-runtime = { version = "28.0.0", path = "../../../substrate/primitives/runtime" }
