[package]
name = "substrate-test-client"
description = "Client testing utilities"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = "6.1"
async-trait = "0.1.57"
codec = { package = "parity-scale-codec", version = "3.6.1" }
futures = "0.3.21"
serde = "1.0.188"
serde_json = "1.0.107"
sc-client-api = { version = "25.0.0", path = "../../client/api" }
sc-client-db = { path = "../../client/db", default-features = false, features = ["test-helpers"], version = "0.32.0" }
sc-consensus = { version = "0.30.0", path = "../../client/consensus/common" }
sc-executor = { version = "0.29.0", path = "../../client/executor" }
sc-offchain = { version = "26.0.0", path = "../../client/offchain" }
sc-service = { path = "../../client/service", default-features = false, features = ["test-helpers"], version = "0.32.0" }
sp-blockchain = { version = "25.0.0", path = "../../primitives/blockchain" }
sp-consensus = { version = "0.29.0", path = "../../primitives/consensus/common" }
sp-core = { version = "25.0.0", path = "../../primitives/core" }
sp-keyring = { version = "28.0.0", path = "../../primitives/keyring" }
sp-keystore = { version = "0.31.0", path = "../../primitives/keystore" }
sp-runtime = { version = "28.0.0", path = "../../primitives/runtime" }
sp-state-machine = { version = "0.32.0", path = "../../primitives/state-machine" }
