[package]
name = "tracing-gum"
version = "4.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Stick logs together with the TraceID as provided by tempo"

[dependencies]
coarsetime = "0.1.22"
tracing = "0.1.35"
jaeger = { package = "polkadot-node-jaeger", path = "../jaeger", version = "4.0.0" }
gum-proc-macro = { package = "tracing-gum-proc-macro", path = "proc-macro", version = "4.0.0" }
polkadot-primitives = { path = "../../primitives", features = ["std"], version = "4.0.0" }
