[package]
name = "xcm-simulator"
description = "Test kit to simulate cross-chain message passing and XCM execution"
version = "4.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
paste = "1.0.7"
frame-support = { version = "25.0.0", path = "../../../substrate/frame/support" }
sp-io = { version = "27.0.0", path = "../../../substrate/primitives/io" }
sp-std = { version = "12.0.0", path = "../../../substrate/primitives/std" }

xcm = { package = "staging-xcm", path = "..", version = "4.0.0" }
xcm-executor = { package = "staging-xcm-executor", path = "../xcm-executor", version = "4.0.0" }
xcm-builder = { package = "staging-xcm-builder", path = "../xcm-builder", version = "4.0.0" }
polkadot-core-primitives = { version = "4.0.0", path = "../../core-primitives" }
polkadot-parachain-primitives = { version = "3.0.0", path = "../../parachain" }
polkadot-runtime-parachains = { version = "4.0.0", path = "../../runtime/parachains" }
