[package]
name = "polkadot-approval-distribution"
version = "4.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-approval-distribution"

[dependencies]
polkadot-node-metrics = { version = "4.0.0", path = "../../metrics" }
polkadot-node-network-protocol = { version = "4.0.0", path = "../protocol" }
polkadot-node-primitives = { version = "4.0.0", path = "../../primitives" }
polkadot-node-subsystem = { version = "4.0.0", path = "../../subsystem" }
polkadot-node-subsystem-util = { version = "4.0.0", path = "../../subsystem-util" }
polkadot-primitives = { version = "4.0.0", path = "../../../primitives" }
polkadot-node-jaeger = { version = "4.0.0", path = "../../jaeger" }
rand = "0.8"

futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../../gum", version = "4.0.0" }

[dev-dependencies]
sp-authority-discovery = { path = "../../../../substrate/primitives/authority-discovery" }
sp-core = { path = "../../../../substrate/primitives/core", features = ["std"] }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }

assert_matches = "1.4.0"
schnorrkel = { version = "0.9.1", default-features = false }
rand_core = "0.5.1" # should match schnorrkel
rand_chacha = "0.3.1"
env_logger = "0.9.0"
log = "0.4.17"
