[package]
name = "sc-transaction-pool-api"
version = "25.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Transaction pool client facing API."

[dependencies]
async-trait = "0.1.57"
codec = { package = "parity-scale-codec", version = "3.6.1" }
futures = "0.3.21"
log = "0.4.17"
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.48"
sp-blockchain = { version = "25.0.0", path = "../../../primitives/blockchain" }
sp-core = { path = "../../../primitives/core", default-features = false, version = "25.0.0" }
sp-runtime = { path = "../../../primitives/runtime", default-features = false, version = "28.0.0" }

[dev-dependencies]
serde_json = "1.0"
