[package]
name = "node-runtime-generate-bags"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Bag threshold generation script for pallet-bag-list and kitchensink-runtime."
publish = false

[dependencies]
kitchensink-runtime = { version = "0.1.0", path = "../../../../bin/node/runtime" }
generate-bags = { version = "25.0.0", path = ".." }

# third-party
clap = { version = "4.4.6", features = ["derive"] }
