[package]
name = "sc-allocator"
version = "20.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Collection of allocator implementations."
documentation = "https://docs.rs/sc-allocator"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = "0.4.17"
thiserror = "1.0.48"
sp-core = { version = "25.0.0", path = "../../primitives/core" }
sp-wasm-interface = { version = "18.0.0", path = "../../primitives/wasm-interface" }
