[package]
name = "sc-consensus"
version = "0.30.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Collection of common consensus specific imlementations for Substrate (client)"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.57"
futures = { version = "0.3.21", features = ["thread-pool"] }
futures-timer = "3.0.1"
libp2p-identity = { version = "0.1.3", features = ["peerid", "ed25519"] }
log = "0.4.17"
mockall = "0.11.3"
parking_lot = "0.12.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.48"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus", version = "0.16.0" }
sc-client-api = { version = "25.0.0", path = "../../api" }
sc-utils = { version = "11.0.0", path = "../../utils" }
sp-api = { version = "23.0.0", path = "../../../primitives/api" }
sp-blockchain = { version = "25.0.0", path = "../../../primitives/blockchain" }
sp-consensus = { version = "0.29.0", path = "../../../primitives/consensus/common" }
sp-core = { version = "25.0.0", path = "../../../primitives/core" }
sp-runtime = { version = "28.0.0", path = "../../../primitives/runtime" }
sp-state-machine = { version = "0.32.0", path = "../../../primitives/state-machine" }

[dev-dependencies]
sp-test-primitives = { path = "../../../primitives/test-primitives" }
