[package]
name = "polkadot-node-core-parachains-inherent"
version = "4.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-node-core-parachains-inherent"

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../../gum", version = "4.0.0" }
thiserror = "1.0.48"
async-trait = "0.1.57"
polkadot-node-subsystem = { version = "4.0.0", path = "../../subsystem" }
polkadot-overseer = { version = "4.0.0", path = "../../overseer" }
polkadot-primitives = { version = "4.0.0", path = "../../../primitives" }
sp-blockchain = { version = "25.0.0", path = "../../../../substrate/primitives/blockchain" }
sp-inherents = { version = "23.0.0", path = "../../../../substrate/primitives/inherents" }
