[package]
name = "asset-hub-westend-integration-tests"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Asset Hub Westend runtime integration tests with xcm-emulator"
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false }
assert_matches = "1.5.0"

# Substrate
sp-runtime = { path = "../../../../../../substrate/primitives/runtime", default-features = false, version = "28.0.0" }
frame-support = { path = "../../../../../../substrate/frame/support", default-features = false, version = "25.0.0" }
frame-system = { path = "../../../../../../substrate/frame/system", default-features = false, version = "25.0.0" }
pallet-balances = { path = "../../../../../../substrate/frame/balances", default-features = false, version = "25.0.0" }
pallet-assets = { path = "../../../../../../substrate/frame/assets", default-features = false, version = "26.0.0" }
pallet-asset-conversion = { path = "../../../../../../substrate/frame/asset-conversion", default-features = false, version = "7.0.0" }
pallet-treasury = { path = "../../../../../../substrate/frame/treasury", default-features = false, version = "24.0.0" }
pallet-asset-rate = { path = "../../../../../../substrate/frame/asset-rate", default-features = false, version = "4.0.0" }

# Polkadot
polkadot-core-primitives = { path = "../../../../../../polkadot/core-primitives", default-features = false, version = "4.0.0" }
polkadot-parachain-primitives = { path = "../../../../../../polkadot/parachain", default-features = false, version = "3.0.0" }
polkadot-runtime-common = { version = "4.0.0", path = "../../../../../../polkadot/runtime/common" }
polkadot-runtime-parachains = { version = "4.0.0", path = "../../../../../../polkadot/runtime/parachains" }
xcm = { package = "staging-xcm", path = "../../../../../../polkadot/xcm", default-features = false, version = "4.0.0" }
xcm-builder = { package = "staging-xcm-builder", path = "../../../../../../polkadot/xcm/xcm-builder", default-features = false, version = "4.0.0" }
xcm-executor = { package = "staging-xcm-executor", path = "../../../../../../polkadot/xcm/xcm-executor", default-features = false, version = "4.0.0" }
pallet-xcm = { path = "../../../../../../polkadot/xcm/pallet-xcm", default-features = false, version = "4.0.0" }
westend-runtime = { path = "../../../../../../polkadot/runtime/westend", default-features = false, version = "4.0.0" }
westend-runtime-constants = { path = "../../../../../../polkadot/runtime/westend/constants", default-features = false, version = "4.0.0" }
parachains-common = { version = "4.0.0", path = "../../../../common" }
asset-hub-westend-runtime = { version = "0.12.0", path = "../../../../runtimes/assets/asset-hub-westend" }
asset-test-utils = { path = "../../../../runtimes/assets/test-utils", default-features = false, version = "4.0.0" }
cumulus-pallet-dmp-queue = { default-features = false, path = "../../../../../pallets/dmp-queue", version = "0.4.0" }
cumulus-pallet-parachain-system = { default-features = false, path = "../../../../../pallets/parachain-system", version = "0.4.0" }

# Local
xcm-emulator = { path = "../../../../../xcm/xcm-emulator", default-features = false, version = "0.2.0" }
integration-tests-common = { path = "../../common", default-features = false, version = "0.1.0" }

[features]
runtime-benchmarks = [
	"asset-hub-westend-runtime/runtime-benchmarks",
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"integration-tests-common/runtime-benchmarks",
	"pallet-asset-conversion/runtime-benchmarks",
	"pallet-asset-rate/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-runtime-common/runtime-benchmarks",
	"polkadot-runtime-parachains/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"westend-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]
