[package]
name = "sp-consensus-aura"
version = "0.29.0"
authors.workspace = true
description = "Primitives for Aura consensus"
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.57", optional = true }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
sp-api = { path = "../../api", default-features = false, version = "23.0.0" }
sp-application-crypto = { path = "../../application-crypto", default-features = false, version = "27.0.0" }
sp-consensus-slots = { path = "../slots", default-features = false, version = "0.29.0" }
sp-inherents = { path = "../../inherents", default-features = false, version = "23.0.0" }
sp-runtime = { path = "../../runtime", default-features = false, version = "28.0.0" }
sp-std = { path = "../../std", default-features = false, version = "12.0.0" }
sp-timestamp = { path = "../../timestamp", default-features = false, version = "23.0.0" }

[features]
default = [ "std" ]
std = [
	"async-trait",
	"codec/std",
	"scale-info/std",
	"sp-api/std",
	"sp-application-crypto/std",
	"sp-consensus-slots/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-timestamp/std",
]

# Serde support without relying on std features.
serde = [
	"scale-info/serde",
	"sp-application-crypto/serde",
	"sp-consensus-slots/serde",
	"sp-runtime/serde",
]
