[package]
name = "xcm-simulator-fuzzer"
description = "Examples of xcm-simulator usage."
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
honggfuzz = "0.5.55"
arbitrary = "1.2.0"
scale-info = { version = "2.10.0", features = ["derive"] }
frame-system = { version = "25.0.0", path = "../../../../substrate/frame/system" }
frame-support = { version = "25.0.0", path = "../../../../substrate/frame/support" }
pallet-balances = { version = "25.0.0", path = "../../../../substrate/frame/balances" }
pallet-message-queue = { version = "28.0.0", path = "../../../../substrate/frame/message-queue" }
sp-std = { version = "12.0.0", path = "../../../../substrate/primitives/std" }
sp-core = { version = "25.0.0", path = "../../../../substrate/primitives/core" }
sp-runtime = { version = "28.0.0", path = "../../../../substrate/primitives/runtime" }
sp-io = { version = "27.0.0", path = "../../../../substrate/primitives/io" }

xcm = { package = "staging-xcm", path = "../..", version = "4.0.0" }
xcm-simulator = { version = "4.0.0", path = ".." }
xcm-executor = { package = "staging-xcm-executor", path = "../../xcm-executor", version = "4.0.0" }
xcm-builder = { package = "staging-xcm-builder", path = "../../xcm-builder", version = "4.0.0" }
pallet-xcm = { version = "4.0.0", path = "../../pallet-xcm" }
polkadot-core-primitives = { version = "4.0.0", path = "../../../core-primitives" }
polkadot-runtime-parachains = { version = "4.0.0", path = "../../../runtime/parachains" }
polkadot-parachain-primitives = { version = "3.0.0", path = "../../../parachain" }

[features]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-runtime-parachains/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]

[[bin]]
path = "src/fuzz.rs"
name = "xcm-fuzzer"
