[package]
name = "integration-tests-common"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Common resources for integration testing with xcm-emulator"
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false }
paste = "1.0.14"

# Substrate
grandpa = { package = "sc-consensus-grandpa", path = "../../../../../substrate/client/consensus/grandpa", version = "0.16.0" }
sp-authority-discovery = { path = "../../../../../substrate/primitives/authority-discovery", default-features = false, version = "23.0.0" }
sp-runtime = { path = "../../../../../substrate/primitives/runtime", default-features = false, version = "28.0.0" }
frame-support = { path = "../../../../../substrate/frame/support", default-features = false, version = "25.0.0" }
sp-core = { path = "../../../../../substrate/primitives/core", default-features = false, version = "25.0.0" }
sp-consensus-babe = { path = "../../../../../substrate/primitives/consensus/babe", default-features = false, version = "0.29.0" }
pallet-assets = { path = "../../../../../substrate/frame/assets", default-features = false, version = "26.0.0" }
pallet-balances = { path = "../../../../../substrate/frame/balances", default-features = false, version = "25.0.0" }
pallet-staking = { path = "../../../../../substrate/frame/staking", default-features = false, version = "25.0.0" }
pallet-message-queue = { path = "../../../../../substrate/frame/message-queue", default-features = false, version = "28.0.0" }
pallet-im-online = { path = "../../../../../substrate/frame/im-online", default-features = false, version = "24.0.0" }
beefy-primitives = { package = "sp-consensus-beefy", path = "../../../../../substrate/primitives/consensus/beefy", version = "10.0.0" }

# Polkadot
polkadot-core-primitives = { path = "../../../../../polkadot/core-primitives", default-features = false, version = "4.0.0" }
polkadot-parachain-primitives = { path = "../../../../../polkadot/parachain", default-features = false, version = "3.0.0" }
polkadot-service = { path = "../../../../../polkadot/node/service", default-features = false, features = ["full-node"], version = "4.0.0" }
polkadot-primitives = { path = "../../../../../polkadot/primitives", default-features = false, version = "4.0.0" }
polkadot-runtime-parachains = { version = "4.0.0", path = "../../../../../polkadot/runtime/parachains" }
rococo-runtime = { version = "4.0.0", path = "../../../../../polkadot/runtime/rococo" }
rococo-runtime-constants = { version = "4.0.0", path = "../../../../../polkadot/runtime/rococo/constants" }
westend-runtime = { version = "4.0.0", path = "../../../../../polkadot/runtime/westend" }
westend-runtime-constants = { version = "4.0.0", path = "../../../../../polkadot/runtime/westend/constants" }
xcm = { package = "staging-xcm", path = "../../../../../polkadot/xcm", default-features = false, version = "4.0.0" }
pallet-xcm = { path = "../../../../../polkadot/xcm/pallet-xcm", default-features = false, version = "4.0.0" }
parachains-common = { version = "4.0.0", path = "../../../common" }
cumulus-primitives-core = { version = "0.4.0", path = "../../../../primitives/core" }
penpal-runtime = { version = "0.11.0", path = "../../../runtimes/testing/penpal" }
asset-hub-polkadot-runtime = { version = "0.12.0", path = "../../../runtimes/assets/asset-hub-polkadot" }
asset-hub-kusama-runtime = { version = "0.12.0", path = "../../../runtimes/assets/asset-hub-kusama" }
asset-hub-rococo-runtime = { version = "0.9.420", path = "../../../runtimes/assets/asset-hub-rococo" }
asset-hub-westend-runtime = { version = "0.12.0", path = "../../../runtimes/assets/asset-hub-westend" }
collectives-polkadot-runtime = { version = "4.0.0", path = "../../../runtimes/collectives/collectives-polkadot" }
bridge-hub-kusama-runtime = { version = "0.4.0", path = "../../../runtimes/bridge-hubs/bridge-hub-kusama" }
bridge-hub-polkadot-runtime = { version = "0.4.0", path = "../../../runtimes/bridge-hubs/bridge-hub-polkadot" }
bridge-hub-rococo-runtime = { version = "0.3.0", path = "../../../runtimes/bridge-hubs/bridge-hub-rococo" }
xcm-emulator = { path = "../../../../xcm/xcm-emulator", default-features = false, version = "0.2.0" }
cumulus-pallet-dmp-queue = { version = "0.4.0", path = "../../../../pallets/dmp-queue" }
cumulus-pallet-xcmp-queue = { path = "../../../../pallets/xcmp-queue", default-features = false, version = "0.4.0" }
cumulus-pallet-parachain-system = { version = "0.4.0", path = "../../../../pallets/parachain-system" }
bp-messages = { version = "0.4.0", path = "../../../../../bridges/primitives/messages" }
pallet-bridge-messages = { version = "0.4.0", path = "../../../../../bridges/modules/messages" }
bridge-runtime-common = { version = "0.4.0", path = "../../../../../bridges/bin/runtime-common" }

[features]
runtime-benchmarks = [
	"asset-hub-kusama-runtime/runtime-benchmarks",
	"asset-hub-polkadot-runtime/runtime-benchmarks",
	"asset-hub-rococo-runtime/runtime-benchmarks",
	"asset-hub-westend-runtime/runtime-benchmarks",
	"bridge-hub-kusama-runtime/runtime-benchmarks",
	"bridge-hub-polkadot-runtime/runtime-benchmarks",
	"bridge-hub-rococo-runtime/runtime-benchmarks",
	"bridge-runtime-common/runtime-benchmarks",
	"collectives-polkadot-runtime/runtime-benchmarks",
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"cumulus-pallet-xcmp-queue/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-bridge-messages/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"penpal-runtime/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-runtime-parachains/runtime-benchmarks",
	"polkadot-service/runtime-benchmarks",
	"rococo-runtime/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"westend-runtime/runtime-benchmarks",
]
