[package]
name = "polkadot-node-core-bitfield-signing"
version = "4.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-node-core-bitfield-signing"

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum", version = "4.0.0" }
polkadot-primitives = { version = "4.0.0", path = "../../../primitives" }
polkadot-node-subsystem = { version = "4.0.0", path = "../../subsystem" }
polkadot-node-subsystem-util = { version = "4.0.0", path = "../../subsystem-util" }
sp-keystore = { version = "0.31.0", path = "../../../../substrate/primitives/keystore" }
wasm-timer = "0.2.5"
thiserror = "1.0.48"

[dev-dependencies]
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../../primitives/test-helpers" }
