[package]
name = "sp-transaction-pool"
version = "23.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Transaction pool runtime facing API."
documentation = "https://docs.rs/sp-transaction-pool"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { path = "../api", default-features = false, version = "23.0.0" }
sp-runtime = { path = "../runtime", default-features = false, version = "28.0.0" }

[features]
default = [ "std" ]
std = [ "sp-api/std", "sp-runtime/std" ]
