[package]
name = "erasure_coding_fuzzer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "erasure_coding_fuzzer"

[dependencies]
polkadot-erasure-coding = { version = "4.0.0", path = ".." }
honggfuzz = "0.5"
polkadot-primitives = { version = "4.0.0", path = "../../primitives" }
primitives = { package = "polkadot-node-primitives", path = "../../node/primitives", version = "4.0.0" }

[[bin]]
name = "reconstruct"
path = "src/reconstruct.rs"

[[bin]]
name = "round_trip"
path = "src/round_trip.rs"
