[package]
name = "sc-client-api"
version = "25.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate client interfaces."
documentation = "https://docs.rs/sc-client-api"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
] }
fnv = "1.0.6"
futures = "0.3.21"
log = "0.4.17"
parking_lot = "0.12.1"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../utils/prometheus", version = "0.16.0" }
sc-executor = { version = "0.29.0", path = "../executor" }
sc-transaction-pool-api = { version = "25.0.0", path = "../transaction-pool/api" }
sc-utils = { version = "11.0.0", path = "../utils" }
sp-api = { version = "23.0.0", path = "../../primitives/api" }
sp-blockchain = { version = "25.0.0", path = "../../primitives/blockchain" }
sp-consensus = { version = "0.29.0", path = "../../primitives/consensus/common" }
sp-core = { path = "../../primitives/core", default-features = false, version = "25.0.0" }
sp-database = { version = "9.0.0", path = "../../primitives/database" }
sp-externalities = { version = "0.23.0", path = "../../primitives/externalities" }
sp-runtime = { path = "../../primitives/runtime", default-features = false, version = "28.0.0" }
sp-state-machine = { version = "0.32.0", path = "../../primitives/state-machine" }
sp-statement-store = { version = "7.0.0", path = "../../primitives/statement-store" }
sp-storage = { version = "17.0.0", path = "../../primitives/storage" }
sp-trie = { version = "26.0.0", path = "../../primitives/trie" }

[dev-dependencies]
thiserror = "1.0.48"
sp-test-primitives = { path = "../../primitives/test-primitives" }
substrate-test-runtime = { path = "../../test-utils/runtime" }
