[package]
name = "bp-bridge-hub-polkadot"
description = "Primitives of BridgeHubWococo parachain runtime."
version = "0.3.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]

# Bridge Dependencies

bp-bridge-hub-cumulus = { path = "../chain-bridge-hub-cumulus", default-features = false, version = "0.4.0" }
bp-runtime = { path = "../runtime", default-features = false, version = "0.4.0" }
bp-messages = { path = "../messages", default-features = false, version = "0.4.0" }

# Substrate Based Dependencies

frame-support = { path = "../../../substrate/frame/support", default-features = false, version = "25.0.0" }
sp-api = { path = "../../../substrate/primitives/api", default-features = false, version = "23.0.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, version = "28.0.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "12.0.0" }

[features]
default = [ "std" ]
std = [
	"bp-bridge-hub-cumulus/std",
	"bp-messages/std",
	"bp-runtime/std",
	"frame-support/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-std/std",
]
