[package]
name = "cumulus-pallet-xcmp-queue"
version = "0.4.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "cumulus-pallet-xcmp-queue"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", features = [ "derive" ], default-features = false }
log = { version = "0.4.20", default-features = false }
rand_chacha = { version = "0.3.0", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

# Substrate
frame-support = { path = "../../../substrate/frame/support", default-features = false, version = "25.0.0" }
frame-system = { path = "../../../substrate/frame/system", default-features = false, version = "25.0.0" }
sp-io = { path = "../../../substrate/primitives/io", default-features = false, version = "27.0.0" }
sp-core = { path = "../../../substrate/primitives/core", default-features = false, version = "25.0.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, version = "28.0.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "12.0.0" }

# Polkadot
polkadot-runtime-common = { path = "../../../polkadot/runtime/common", default-features = false, version = "4.0.0" }
polkadot-runtime-parachains = { path = "../../../polkadot/runtime/parachains", default-features = false, version = "4.0.0" }
xcm = { package = "staging-xcm", path = "../../../polkadot/xcm", default-features = false, version = "4.0.0" }
xcm-executor = { package = "staging-xcm-executor", path = "../../../polkadot/xcm/xcm-executor", default-features = false, version = "4.0.0" }

# Cumulus
cumulus-primitives-core = { path = "../../primitives/core", default-features = false, version = "0.4.0" }

# Optional import for benchmarking
frame-benchmarking = { path = "../../../substrate/frame/benchmarking", default-features = false, optional = true, version = "25.0.0" }

# Bridges
bp-xcm-bridge-hub-router = { path = "../../../bridges/primitives/xcm-bridge-hub-router", default-features = false, optional = true, version = "0.3.0" }

[dev-dependencies]
sp-core = { path = "../../../substrate/primitives/core" }
pallet-balances = { path = "../../../substrate/frame/balances" }

# Polkadot
xcm-builder = { package = "staging-xcm-builder", path = "../../../polkadot/xcm/xcm-builder" }

# Cumulus
cumulus-pallet-parachain-system = { path = "../parachain-system", features = ["parameterized-consensus-hook"] }

[features]
default = [ "std" ]
std = [
	"bp-xcm-bridge-hub-router?/std",
	"codec/std",
	"cumulus-primitives-core/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"polkadot-runtime-common/std",
	"polkadot-runtime-parachains/std",
	"rand_chacha/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-executor/std",
	"xcm/std",
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"polkadot-runtime-common/runtime-benchmarks",
	"polkadot-runtime-parachains/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"polkadot-runtime-common/try-runtime",
	"polkadot-runtime-parachains/try-runtime",
	"sp-runtime/try-runtime",
]
bridging = [ "bp-xcm-bridge-hub-router" ]
