[package]
name = "substrate-frame-rpc-support"
version = "26.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate RPC for FRAME's support"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
jsonrpsee = { version = "0.16.2", features = ["jsonrpsee-types"] }
serde = "1"
frame-support = { version = "25.0.0", path = "../../../../frame/support" }
sc-rpc-api = { version = "0.30.0", path = "../../../../client/rpc-api" }
sp-storage = { version = "17.0.0", path = "../../../../primitives/storage" }

[dev-dependencies]
scale-info = "2.10.0"
jsonrpsee = { version = "0.16.2", features = ["ws-client", "jsonrpsee-types"] }
tokio = "1.22.0"
sp-core = { path = "../../../../primitives/core" }
sp-runtime = { path = "../../../../primitives/runtime" }
frame-system = { path = "../../../../frame/system" }
