[package]
name = "sc-rpc"
version = "26.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate Client RPC"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
futures = "0.3.21"
jsonrpsee = { version = "0.16.2", features = ["server"] }
log = "0.4.17"
parking_lot = "0.12.1"
serde_json = "1.0.107"
sc-block-builder = { version = "0.30.0", path = "../block-builder" }
sc-chain-spec = { version = "24.0.0", path = "../chain-spec" }
sc-client-api = { version = "25.0.0", path = "../api" }
sc-mixnet = { version = "0.1.0", path = "../mixnet" }
sc-rpc-api = { version = "0.30.0", path = "../rpc-api" }
sc-tracing = { version = "25.0.0", path = "../tracing" }
sc-transaction-pool-api = { version = "25.0.0", path = "../transaction-pool/api" }
sc-utils = { version = "11.0.0", path = "../utils" }
sp-api = { version = "23.0.0", path = "../../primitives/api" }
sp-blockchain = { version = "25.0.0", path = "../../primitives/blockchain" }
sp-core = { version = "25.0.0", path = "../../primitives/core" }
sp-keystore = { version = "0.31.0", path = "../../primitives/keystore" }
sp-offchain = { version = "23.0.0", path = "../../primitives/offchain" }
sp-rpc = { version = "23.0.0", path = "../../primitives/rpc" }
sp-runtime = { version = "28.0.0", path = "../../primitives/runtime" }
sp-session = { version = "24.0.0", path = "../../primitives/session" }
sp-version = { version = "26.0.0", path = "../../primitives/version" }
sp-statement-store = { version = "7.0.0", path = "../../primitives/statement-store" }

tokio = "1.22.0"

[dev-dependencies]
env_logger = "0.9"
assert_matches = "1.3.0"
sc-block-builder = { path = "../block-builder" }
sc-network = { path = "../network" }
sc-network-common = { path = "../network/common" }
sc-transaction-pool = { path = "../transaction-pool" }
sp-consensus = { path = "../../primitives/consensus/common" }
tokio = "1.22.0"
sp-io = { path = "../../primitives/io" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }
pretty_assertions = "1.2.1"

[features]
test-helpers = []
