[package]
name = "frame-system"
version = "25.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME system module"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
cfg-if = "1.0"
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
log = { version = "0.4.17", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive", "serde"] }
serde = { version = "1.0.188", default-features = false, features = ["derive", "alloc"] }
frame-support = { path = "../support", default-features = false, version = "25.0.0" }
sp-core = { path = "../../primitives/core", default-features = false, features = ["serde"], version = "25.0.0" }
sp-io = { path = "../../primitives/io", default-features = false, version = "27.0.0" }
sp-runtime = { path = "../../primitives/runtime", default-features = false, features = ["serde"], version = "28.0.0" }
sp-std = { path = "../../primitives/std", default-features = false, version = "12.0.0" }
sp-version = { path = "../../primitives/version", default-features = false, features = ["serde"], version = "26.0.0" }
sp-weights = { path = "../../primitives/weights", default-features = false, features = ["serde"], version = "24.0.0" }

[dev-dependencies]
criterion = "0.4.0"
sp-externalities = { path = "../../primitives/externalities" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"frame-support/std",
	"log/std",
	"scale-info/std",
	"serde/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-version/std",
	"sp-weights/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [ "frame-support/try-runtime", "sp-runtime/try-runtime" ]

[[bench]]
name = "bench"
harness = false
