[package]
name = "node-primitives"
version = "0.1.0"
authors.workspace = true
description = "Substrate node low-level primitives."
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-core = { path = "../../../primitives/core", default-features = false, version = "25.0.0" }
sp-runtime = { path = "../../../primitives/runtime", default-features = false, version = "28.0.0" }

[features]
default = [ "std" ]
std = [ "sp-core/std", "sp-runtime/std" ]
