[package]
name = "polkadot-node-core-approval-voting"
version = "4.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-node-core-approval-voting"

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["bit-vec", "derive"] }
gum = { package = "tracing-gum", path = "../../gum", version = "4.0.0" }
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
schnellru = "0.2.1"
merlin = "2.0"
schnorrkel = "0.9.1"
kvdb = "0.13.0"
derive_more = "0.99.17"
thiserror = "1.0.48"
polkadot-node-subsystem = { version = "4.0.0", path = "../../subsystem" }
polkadot-node-subsystem-util = { version = "4.0.0", path = "../../subsystem-util" }
polkadot-overseer = { version = "4.0.0", path = "../../overseer" }
polkadot-primitives = { version = "4.0.0", path = "../../../primitives" }
polkadot-node-primitives = { version = "4.0.0", path = "../../primitives" }
polkadot-node-jaeger = { version = "4.0.0", path = "../../jaeger" }

sc-keystore = { path = "../../../../substrate/client/keystore", default-features = false, version = "22.0.0" }
sp-consensus = { path = "../../../../substrate/primitives/consensus/common", default-features = false, version = "0.29.0" }
sp-consensus-slots = { path = "../../../../substrate/primitives/consensus/slots", default-features = false, version = "0.29.0" }
sp-application-crypto = { path = "../../../../substrate/primitives/application-crypto", default-features = false, features = ["full_crypto"], version = "27.0.0" }
sp-runtime = { path = "../../../../substrate/primitives/runtime", default-features = false, version = "28.0.0" }

[dev-dependencies]
async-trait = "0.1.57"
parking_lot = "0.12.0"
rand_core = "0.5.1" #                                                                       should match schnorrkel
sp-keyring = { path = "../../../../substrate/primitives/keyring" }
sp-keystore = { path = "../../../../substrate/primitives/keystore" }
sp-core = { path = "../../../../substrate/primitives/core" }
sp-consensus-babe = { path = "../../../../substrate/primitives/consensus/babe" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
assert_matches = "1.4.0"
kvdb-memorydb = "0.13.0"
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../../primitives/test-helpers" }
