[package]
name = "sp-npos-elections-fuzzer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Fuzzer for phragmén implementation."
documentation = "https://docs.rs/sp-npos-elections-fuzzer"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
honggfuzz = "0.5"
rand = { version = "0.8", features = ["std", "small_rng"] }
sp-npos-elections = { version = "23.0.0", path = ".." }
sp-runtime = { version = "28.0.0", path = "../../runtime" }

[[bin]]
name = "reduce"
path = "src/reduce.rs"

[[bin]]
name = "phragmen_balancing"
path = "src/phragmen_balancing.rs"

[[bin]]
name = "phragmms_balancing"
path = "src/phragmms_balancing.rs"

[[bin]]
name = "phragmen_pjr"
path = "src/phragmen_pjr.rs"
