[package]
name = "polkadot-node-core-chain-api"
version = "4.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-node-core-chain-api"

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum", version = "4.0.0" }
sp-blockchain = { version = "25.0.0", path = "../../../../substrate/primitives/blockchain" }
polkadot-primitives = { version = "4.0.0", path = "../../../primitives" }
polkadot-node-metrics = { version = "4.0.0", path = "../../metrics" }
polkadot-node-subsystem = { version = "4.0.0", path = "../../subsystem" }
sc-client-api = { version = "25.0.0", path = "../../../../substrate/client/api" }
sc-consensus-babe = { version = "0.31.0", path = "../../../../substrate/client/consensus/babe" }

[dev-dependencies]
futures = { version = "0.3.21", features = ["thread-pool"] }
maplit = "1.0.2"
parity-scale-codec = "3.6.1"
polkadot-node-primitives = { path = "../../primitives" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { path = "../../../../substrate/primitives/core" }
