[package]
name = "sc-block-builder"
version = "0.30.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate block builder"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", features = [
	"derive",
] }
sc-client-api = { version = "25.0.0", path = "../api" }
sp-api = { version = "23.0.0", path = "../../primitives/api" }
sp-block-builder = { version = "23.0.0", path = "../../primitives/block-builder" }
sp-blockchain = { version = "25.0.0", path = "../../primitives/blockchain" }
sp-core = { version = "25.0.0", path = "../../primitives/core" }
sp-inherents = { version = "23.0.0", path = "../../primitives/inherents" }
sp-runtime = { version = "28.0.0", path = "../../primitives/runtime" }

[dev-dependencies]
sp-state-machine = { path = "../../primitives/state-machine" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }
