[package]
name = "bridge-hub-test-utils"
version = "0.4.0"
authors.workspace = true
edition.workspace = true
description = "Utils for BridgeHub testing"
license = "Apache-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] }
log = { version = "0.4.20", default-features = false }

# Substrate
frame-benchmarking = { path = "../../../../../substrate/frame/benchmarking", default-features = false, optional = true, version = "25.0.0" }
frame-executive = { path = "../../../../../substrate/frame/executive", default-features = false, version = "25.0.0" }
frame-support = { path = "../../../../../substrate/frame/support", default-features = false, version = "25.0.0" }
frame-system = { path = "../../../../../substrate/frame/system", default-features = false, version = "25.0.0" }
sp-core = { path = "../../../../../substrate/primitives/core", default-features = false, version = "25.0.0" }
sp-io = { path = "../../../../../substrate/primitives/io", default-features = false, version = "27.0.0" }
sp-keyring = { version = "28.0.0", path = "../../../../../substrate/primitives/keyring" }
sp-runtime = { path = "../../../../../substrate/primitives/runtime", default-features = false, version = "28.0.0" }
sp-tracing = { version = "14.0.0", path = "../../../../../substrate/primitives/tracing" }
pallet-balances = { path = "../../../../../substrate/frame/balances", default-features = false, version = "25.0.0" }
pallet-utility = { path = "../../../../../substrate/frame/utility", default-features = false, version = "25.0.0" }
pallet-session = { path = "../../../../../substrate/frame/session", default-features = false, version = "25.0.0" }
asset-test-utils = { version = "4.0.0", path = "../../assets/test-utils" }
cumulus-pallet-dmp-queue = { path = "../../../../pallets/dmp-queue", default-features = false, version = "0.4.0" }
cumulus-pallet-parachain-system = { path = "../../../../pallets/parachain-system", default-features = false, features = ["parameterized-consensus-hook"], version = "0.4.0" }
cumulus-pallet-xcmp-queue = { path = "../../../../pallets/xcmp-queue", default-features = false, version = "0.4.0" }
pallet-collator-selection = { path = "../../../../pallets/collator-selection", default-features = false, version = "6.0.0" }
parachain-info = { package = "staging-parachain-info", path = "../../../pallets/parachain-info", default-features = false, version = "0.4.0" }
parachains-common = { path = "../../../common", default-features = false, version = "4.0.0" }
parachains-runtimes-test-utils = { path = "../../test-utils", default-features = false, version = "4.0.0" }

# Polkadot
pallet-xcm = { path = "../../../../../polkadot/xcm/pallet-xcm", default-features = false, version = "4.0.0" }
pallet-xcm-benchmarks = { path = "../../../../../polkadot/xcm/pallet-xcm-benchmarks", default-features = false, optional = true, version = "4.0.0" }
xcm = { package = "staging-xcm", path = "../../../../../polkadot/xcm", default-features = false, version = "4.0.0" }
xcm-builder = { package = "staging-xcm-builder", path = "../../../../../polkadot/xcm/xcm-builder", default-features = false, version = "4.0.0" }
xcm-executor = { package = "staging-xcm-executor", path = "../../../../../polkadot/xcm/xcm-executor", default-features = false, version = "4.0.0" }

# Bridges
bp-bridge-hub-rococo = { path = "../../../../../bridges/primitives/chain-bridge-hub-rococo", default-features = false, version = "0.4.0" }
bp-bridge-hub-wococo = { path = "../../../../../bridges/primitives/chain-bridge-hub-wococo", default-features = false, version = "0.4.0" }
bp-header-chain = { path = "../../../../../bridges/primitives/header-chain", default-features = false, version = "0.4.0" }
bp-messages = { path = "../../../../../bridges/primitives/messages", default-features = false, version = "0.4.0" }
bp-parachains = { path = "../../../../../bridges/primitives/parachains", default-features = false, version = "0.4.0" }
bp-polkadot-core = { path = "../../../../../bridges/primitives/polkadot-core", default-features = false, version = "0.4.0" }
bp-relayers = { path = "../../../../../bridges/primitives/relayers", default-features = false, version = "0.4.0" }
bp-runtime = { path = "../../../../../bridges/primitives/runtime", default-features = false, version = "0.4.0" }
bp-test-utils = { path = "../../../../../bridges/primitives/test-utils", default-features = false, version = "0.4.0" }
pallet-bridge-grandpa = { path = "../../../../../bridges/modules/grandpa", default-features = false, version = "0.4.0" }
pallet-bridge-parachains = { path = "../../../../../bridges/modules/parachains", default-features = false, version = "0.4.0" }
pallet-bridge-messages = { path = "../../../../../bridges/modules/messages", default-features = false, version = "0.4.0" }
pallet-bridge-relayers = { path = "../../../../../bridges/modules/relayers", default-features = false, version = "0.4.0" }
bridge-runtime-common = { path = "../../../../../bridges/bin/runtime-common", default-features = false, version = "0.4.0" }

[features]
default = [ "std" ]
std = [
	"asset-test-utils/std",
	"bp-bridge-hub-rococo/std",
	"bp-bridge-hub-wococo/std",
	"bp-header-chain/std",
	"bp-messages/std",
	"bp-parachains/std",
	"bp-polkadot-core/std",
	"bp-relayers/std",
	"bp-runtime/std",
	"bp-test-utils/std",
	"bridge-runtime-common/std",
	"codec/std",
	"cumulus-pallet-dmp-queue/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-xcmp-queue/std",
	"frame-benchmarking/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-balances/std",
	"pallet-bridge-grandpa/std",
	"pallet-bridge-messages/std",
	"pallet-bridge-parachains/std",
	"pallet-bridge-relayers/std",
	"pallet-collator-selection/std",
	"pallet-session/std",
	"pallet-utility/std",
	"pallet-xcm-benchmarks?/std",
	"pallet-xcm/std",
	"parachain-info/std",
	"parachains-common/std",
	"parachains-runtimes-test-utils/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
]
