[package]
name = "sp-consensus-pow"
version = "0.29.0"
authors.workspace = true
description = "Primitives for Aura consensus"
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
sp-api = { path = "../../api", default-features = false, version = "23.0.0" }
sp-core = { path = "../../core", default-features = false, version = "25.0.0" }
sp-runtime = { path = "../../runtime", default-features = false, version = "28.0.0" }
sp-std = { path = "../../std", default-features = false, version = "12.0.0" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
