[package]
name = "sp-timestamp"
version = "23.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate core types and inherents for timestamps."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.57", optional = true }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.48", optional = true }
sp-inherents = { path = "../inherents", default-features = false, version = "23.0.0" }
sp-runtime = { path = "../runtime", default-features = false, version = "28.0.0" }
sp-std = { path = "../std", default-features = false, version = "12.0.0" }

[features]
default = [ "std" ]
std = [
	"async-trait",
	"codec/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-std/std",
	"thiserror",
]
