[package]
name = "sc-consensus-pow"
version = "0.30.0"
authors.workspace = true
description = "PoW consensus algorithm for substrate"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.57"
codec = { package = "parity-scale-codec", version = "3.6.1", features = ["derive"] }
futures = "0.3.21"
futures-timer = "3.0.1"
log = "0.4.17"
parking_lot = "0.12.1"
thiserror = "1.0"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus", version = "0.16.0" }
sc-client-api = { version = "25.0.0", path = "../../api" }
sc-consensus = { version = "0.30.0", path = "../common" }
sp-api = { version = "23.0.0", path = "../../../primitives/api" }
sp-block-builder = { version = "23.0.0", path = "../../../primitives/block-builder" }
sp-blockchain = { version = "25.0.0", path = "../../../primitives/blockchain" }
sp-consensus = { version = "0.29.0", path = "../../../primitives/consensus/common" }
sp-consensus-pow = { version = "0.29.0", path = "../../../primitives/consensus/pow" }
sp-core = { version = "25.0.0", path = "../../../primitives/core" }
sp-inherents = { version = "23.0.0", path = "../../../primitives/inherents" }
sp-runtime = { version = "28.0.0", path = "../../../primitives/runtime" }
