[package]
name = "sc-consensus-epochs"
version = "0.30.0"
authors.workspace = true
description = "Generic epochs-based utilities for consensus"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", features = ["derive"] }
fork-tree = { version = "11.0.0", path = "../../../utils/fork-tree" }
sc-client-api = { version = "25.0.0", path = "../../api" }
sc-consensus = { version = "0.30.0", path = "../common" }
sp-blockchain = { version = "25.0.0", path = "../../../primitives/blockchain" }
sp-runtime = { version = "28.0.0", path = "../../../primitives/runtime" }
