[package]
name = "polkadot-gossip-support"
version = "4.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-gossip-support"

[dependencies]
sp-application-crypto = { version = "27.0.0", path = "../../../../substrate/primitives/application-crypto" }
sp-keystore = { version = "0.31.0", path = "../../../../substrate/primitives/keystore" }
sp-core = { version = "25.0.0", path = "../../../../substrate/primitives/core" }
sc-network = { version = "0.31.0", path = "../../../../substrate/client/network" }
sc-network-common = { version = "0.30.0", path = "../../../../substrate/client/network/common" }
polkadot-node-network-protocol = { version = "4.0.0", path = "../protocol" }
polkadot-node-subsystem = { version = "4.0.0", path = "../../subsystem" }
polkadot-node-subsystem-util = { version = "4.0.0", path = "../../subsystem-util" }
polkadot-primitives = { version = "4.0.0", path = "../../../primitives" }

futures = "0.3.21"
futures-timer = "3.0.2"
rand = { version = "0.8.5", default-features = false }
rand_chacha = { version = "0.3.1", default-features = false }
gum = { package = "tracing-gum", path = "../../gum", version = "4.0.0" }

[dev-dependencies]
sp-keyring = { path = "../../../../substrate/primitives/keyring" }
sp-consensus-babe = { path = "../../../../substrate/primitives/consensus/babe" }
sp-tracing = { path = "../../../../substrate/primitives/tracing" }
sp-authority-discovery = { path = "../../../../substrate/primitives/authority-discovery" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }

assert_matches = "1.4.0"
async-trait = "0.1.57"
lazy_static = "1.4.0"
