[package]
name = "sp-consensus-grandpa"
version = "10.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Primitives for GRANDPA integration, suitable for WASM compilation."
documentation = "https://docs.rs/sp-consensus-grandpa"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
grandpa = { package = "finality-grandpa", version = "0.16.2", default-features = false, features = ["derive-codec"] }
log = { version = "0.4.17", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.188", features = ["derive", "alloc"], default-features = false, optional = true }
sp-api = { path = "../../api", default-features = false, version = "23.0.0" }
sp-application-crypto = { path = "../../application-crypto", default-features = false, version = "27.0.0" }
sp-core = { path = "../../core", default-features = false, version = "25.0.0" }
sp-keystore = { path = "../../keystore", default-features = false, optional = true, version = "0.31.0" }
sp-runtime = { path = "../../runtime", default-features = false, version = "28.0.0" }
sp-std = { path = "../../std", default-features = false, version = "12.0.0" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"grandpa/std",
	"log/std",
	"scale-info/std",
	"serde/std",
	"sp-api/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-keystore/std",
	"sp-runtime/std",
	"sp-std/std",
]

# Serde support without relying on std features.
serde = [
	"dep:serde",
	"scale-info/serde",
	"sp-application-crypto/serde",
	"sp-core/serde",
	"sp-runtime/serde",
]
