[package]
name = "staging-node-executor"
version = "0.1.0"
authors.workspace = true
description = "Substrate node implementation in Rust."
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
scale-info = { version = "2.10.0", features = ["derive"] }
frame-benchmarking = { version = "25.0.0", path = "../../../frame/benchmarking" }
node-primitives = { version = "0.1.0", path = "../primitives" }
kitchensink-runtime = { version = "0.1.0", path = "../runtime" }
sc-executor = { version = "0.29.0", path = "../../../client/executor" }
sp-core = { version = "25.0.0", path = "../../../primitives/core" }
sp-keystore = { version = "0.31.0", path = "../../../primitives/keystore" }
sp-state-machine = { version = "0.32.0", path = "../../../primitives/state-machine" }
sp-tracing = { version = "14.0.0", path = "../../../primitives/tracing" }
sp-trie = { version = "26.0.0", path = "../../../primitives/trie" }
sp-statement-store = { version = "7.0.0", path = "../../../primitives/statement-store" }

[dev-dependencies]
criterion = "0.4.0"
futures = "0.3.21"
wat = "1.0"
frame-support = { path = "../../../frame/support" }
frame-system = { path = "../../../frame/system" }
node-testing = { path = "../testing" }
pallet-balances = { path = "../../../frame/balances" }
pallet-contracts = { path = "../../../frame/contracts" }
pallet-im-online = { path = "../../../frame/im-online" }
pallet-glutton = { path = "../../../frame/glutton" }
pallet-sudo = { path = "../../../frame/sudo" }
pallet-timestamp = { path = "../../../frame/timestamp" }
pallet-treasury = { path = "../../../frame/treasury" }
pallet-transaction-payment = { path = "../../../frame/transaction-payment" }
sp-application-crypto = { path = "../../../primitives/application-crypto" }
pallet-root-testing = { path = "../../../frame/root-testing" }
sp-consensus-babe = { path = "../../../primitives/consensus/babe" }
sp-externalities = { path = "../../../primitives/externalities" }
sp-keyring = { path = "../../../primitives/keyring" }
sp-runtime = { path = "../../../primitives/runtime" }

[features]
stress-test = []

[[bench]]
name = "bench"
harness = false
