[package]
name = "staging-node-inspect"
version = "0.9.0"
authors.workspace = true
description = "Substrate node block inspection tool."
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.6.1" }
thiserror = "1.0"
sc-cli = { version = "0.33.0", path = "../../../client/cli" }
sc-client-api = { version = "25.0.0", path = "../../../client/api" }
sc-service = { path = "../../../client/service", default-features = false, version = "0.32.0" }
sp-blockchain = { version = "25.0.0", path = "../../../primitives/blockchain" }
sp-core = { version = "25.0.0", path = "../../../primitives/core" }
sp-runtime = { version = "28.0.0", path = "../../../primitives/runtime" }
