[package]
name = "polkadot-test-malus"
description = "Misbehaving nodes for local testnets, system and Simnet tests."
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
publish = false

[[bin]]
name = "malus"
path = "src/malus.rs"

# Use artifact dependencies once stable.
# See https://github.com/rust-lang/cargo/issues/9096.
[[bin]]
name = "polkadot-execute-worker"
path = "../../src/bin/execute-worker.rs"
# Prevent rustdoc error. Already documented from top-level Cargo.toml.
doc = false
[[bin]]
name = "polkadot-prepare-worker"
path = "../../src/bin/prepare-worker.rs"
# Prevent rustdoc error. Already documented from top-level Cargo.toml.
doc = false

[dependencies]
polkadot-cli = { path = "../../cli", features = ["malus", "rococo-native", "westend-native"], version = "4.0.0" }
polkadot-node-subsystem = { version = "4.0.0", path = "../subsystem" }
polkadot-node-subsystem-util = { version = "4.0.0", path = "../subsystem-util" }
polkadot-node-subsystem-types = { version = "4.0.0", path = "../subsystem-types" }
polkadot-node-core-dispute-coordinator = { version = "4.0.0", path = "../core/dispute-coordinator" }
polkadot-node-core-candidate-validation = { version = "4.0.0", path = "../core/candidate-validation" }
polkadot-node-core-backing = { version = "4.0.0", path = "../core/backing" }
polkadot-node-primitives = { version = "4.0.0", path = "../primitives" }
polkadot-primitives = { version = "4.0.0", path = "../../primitives" }
color-eyre = { version = "0.6.1", default-features = false }
assert_matches = "1.5"
async-trait = "0.1.57"
sp-keystore = { version = "0.31.0", path = "../../../substrate/primitives/keystore" }
sp-core = { version = "25.0.0", path = "../../../substrate/primitives/core" }
clap = { version = "4.4.6", features = ["derive"] }
futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../gum", version = "4.0.0" }
erasure = { package = "polkadot-erasure-coding", path = "../../erasure-coding", version = "4.0.0" }
rand = "0.8.5"

# Required for worker binaries to build.
polkadot-node-core-pvf-common = { path = "../core/pvf/common", features = ["test-utils"], version = "4.0.0" }
polkadot-node-core-pvf-execute-worker = { version = "4.0.0", path = "../core/pvf/execute-worker" }
polkadot-node-core-pvf-prepare-worker = { version = "4.0.0", path = "../core/pvf/prepare-worker" }

[dev-dependencies]
polkadot-node-subsystem-test-helpers = { path = "../subsystem-test-helpers" }
sp-core = { path = "../../../substrate/primitives/core" }
futures = { version = "0.3.21", features = ["thread-pool"] }

[build-dependencies]
substrate-build-script-utils = { version = "9.0.0", path = "../../../substrate/utils/build-script-utils" }

[features]
default = []
fast-runtime = [ "polkadot-cli/fast-runtime" ]
