[package]
name = "bp-test-utils"
version = "0.4.0"
description = "Utilities for testing substrate-based runtime bridge code"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
bp-header-chain = { path = "../header-chain", default-features = false, version = "0.4.0" }
bp-parachains = { path = "../parachains", default-features = false, version = "0.4.0" }
bp-polkadot-core = { path = "../polkadot-core", default-features = false, version = "0.4.0" }
bp-runtime = { path = "../runtime", default-features = false, version = "0.4.0" }
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false }
ed25519-dalek = { version = "2.0", default-features = false }
finality-grandpa = { version = "0.16.2", default-features = false }
sp-application-crypto = { path = "../../../substrate/primitives/application-crypto", default-features = false, version = "27.0.0" }
sp-consensus-grandpa = { path = "../../../substrate/primitives/consensus/grandpa", default-features = false, version = "10.0.0" }
sp-core = { path = "../../../substrate/primitives/core", default-features = false, version = "25.0.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, version = "28.0.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "12.0.0" }
sp-trie = { path = "../../../substrate/primitives/trie", default-features = false, version = "26.0.0" }

[features]
default = [ "std" ]
std = [
	"bp-header-chain/std",
	"bp-parachains/std",
	"bp-polkadot-core/std",
	"bp-runtime/std",
	"codec/std",
	"ed25519-dalek/std",
	"finality-grandpa/std",
	"sp-application-crypto/std",
	"sp-consensus-grandpa/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-trie/std",
]
