[package]
name = "sc-chain-spec"
version = "24.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate chain configurations."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
memmap2 = "0.5.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
sc-client-api = { version = "25.0.0", path = "../api" }
sc-chain-spec-derive = { version = "10.0.0", path = "derive" }
sc-executor = { version = "0.29.0", path = "../executor" }
sc-network = { version = "0.31.0", path = "../network" }
sc-telemetry = { version = "12.0.0", path = "../telemetry" }
sp-blockchain = { version = "25.0.0", path = "../../primitives/blockchain" }
sp-core = { version = "25.0.0", path = "../../primitives/core" }
sp-runtime = { version = "28.0.0", path = "../../primitives/runtime" }
sp-state-machine = { version = "0.32.0", path = "../../primitives/state-machine" }
