[package]
name = "cumulus-client-consensus-aura"
description = "AURA consensus algorithm for parachains"
version = "0.4.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
async-trait = "0.1.73"
codec = { package = "parity-scale-codec", version = "3.0.0", features = [ "derive" ] }
futures = "0.3.28"
tracing = "0.1.37"
schnellru = "0.2.1"
sc-client-api = { version = "25.0.0", path = "../../../../substrate/client/api" }
sc-consensus = { version = "0.30.0", path = "../../../../substrate/client/consensus/common" }
sc-consensus-aura = { version = "0.31.0", path = "../../../../substrate/client/consensus/aura" }
sc-consensus-babe = { version = "0.31.0", path = "../../../../substrate/client/consensus/babe" }
sc-consensus-slots = { version = "0.30.0", path = "../../../../substrate/client/consensus/slots" }
sc-telemetry = { version = "12.0.0", path = "../../../../substrate/client/telemetry" }
sp-api = { version = "23.0.0", path = "../../../../substrate/primitives/api" }
sp-application-crypto = { version = "27.0.0", path = "../../../../substrate/primitives/application-crypto" }
sp-block-builder = { version = "23.0.0", path = "../../../../substrate/primitives/block-builder" }
sp-blockchain = { version = "25.0.0", path = "../../../../substrate/primitives/blockchain" }
sp-consensus = { version = "0.29.0", path = "../../../../substrate/primitives/consensus/common" }
sp-consensus-aura = { version = "0.29.0", path = "../../../../substrate/primitives/consensus/aura" }
sp-core = { version = "25.0.0", path = "../../../../substrate/primitives/core" }
sp-inherents = { version = "23.0.0", path = "../../../../substrate/primitives/inherents" }
sp-keystore = { version = "0.31.0", path = "../../../../substrate/primitives/keystore" }
sp-runtime = { version = "28.0.0", path = "../../../../substrate/primitives/runtime" }
sp-timestamp = { version = "23.0.0", path = "../../../../substrate/primitives/timestamp" }
sp-state-machine = { version = "0.32.0", path = "../../../../substrate/primitives/state-machine" }
substrate-prometheus-endpoint = { version = "0.16.0", path = "../../../../substrate/utils/prometheus" }
cumulus-client-consensus-common = { version = "0.4.0", path = "../common" }
cumulus-relay-chain-interface = { version = "0.4.0", path = "../../relay-chain-interface" }
cumulus-client-consensus-proposer = { version = "0.4.0", path = "../proposer" }
cumulus-primitives-aura = { version = "0.4.0", path = "../../../primitives/aura" }
cumulus-primitives-core = { version = "0.4.0", path = "../../../primitives/core" }
cumulus-primitives-parachain-inherent = { version = "0.4.0", path = "../../../primitives/parachain-inherent" }
cumulus-client-collator = { version = "0.4.0", path = "../../collator" }
polkadot-primitives = { version = "4.0.0", path = "../../../../polkadot/primitives" }
polkadot-node-primitives = { version = "4.0.0", path = "../../../../polkadot/node/primitives" }
polkadot-node-subsystem = { version = "4.0.0", path = "../../../../polkadot/node/subsystem" }
polkadot-overseer = { version = "4.0.0", path = "../../../../polkadot/node/overseer" }
