[package]
name = "substrate-state-trie-migration-rpc"
version = "24.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Node-specific RPC methods for interaction with state trie migration."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false }
serde = { version = "1", features = ["derive"] }
sp-core = { version = "25.0.0", path = "../../../../primitives/core" }
sp-state-machine = { version = "0.32.0", path = "../../../../primitives/state-machine" }
sp-trie = { version = "26.0.0", path = "../../../../primitives/trie" }
trie-db = "0.28.0"

jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
sc-client-api = { version = "25.0.0", path = "../../../../client/api" }
sc-rpc-api = { version = "0.30.0", path = "../../../../client/rpc-api" }
sp-runtime = { version = "28.0.0", path = "../../../../primitives/runtime" }

[dev-dependencies]
serde_json = "1"
