[package]
description = "Substrate sync network protocol"
name = "sc-network-sync"
version = "0.30.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors.workspace = true
edition.workspace = true
homepage = "https://substrate.io"
repository.workspace = true
documentation = "https://docs.rs/sc-network-sync"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
prost-build = "0.11"

[dependencies]
array-bytes = "6.1"
async-channel = "1.8.0"
async-trait = "0.1.58"
codec = { package = "parity-scale-codec", version = "3.6.1", features = ["derive"] }
futures = "0.3.21"
futures-timer = "3.0.2"
libp2p = "0.51.3"
log = "0.4.17"
mockall = "0.11.3"
prost = "0.11"
schnellru = "0.2.1"
smallvec = "1.11.0"
thiserror = "1.0"
tokio-stream = "0.1.14"
fork-tree = { version = "11.0.0", path = "../../../utils/fork-tree" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus", version = "0.16.0" }
sc-client-api = { version = "25.0.0", path = "../../api" }
sc-consensus = { version = "0.30.0", path = "../../consensus/common" }
sc-network = { version = "0.31.0", path = ".." }
sc-network-common = { version = "0.30.0", path = "../common" }
sc-utils = { version = "11.0.0", path = "../../utils" }
sp-arithmetic = { version = "20.0.0", path = "../../../primitives/arithmetic" }
sp-blockchain = { version = "25.0.0", path = "../../../primitives/blockchain" }
sp-consensus = { version = "0.29.0", path = "../../../primitives/consensus/common" }
sp-core = { version = "25.0.0", path = "../../../primitives/core" }
sp-consensus-grandpa = { version = "10.0.0", path = "../../../primitives/consensus/grandpa" }
sp-runtime = { version = "28.0.0", path = "../../../primitives/runtime" }

[dev-dependencies]
tokio = { version = "1.22.0", features = ["macros"] }
quickcheck = { version = "1.0.3", default-features = false }
sc-block-builder = { path = "../../block-builder" }
sp-test-primitives = { path = "../../../primitives/test-primitives" }
sp-tracing = { path = "../../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../../test-utils/runtime/client" }
