[package]
name = "cumulus-primitives-aura"
version = "0.4.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "cumulus-primitives-aura"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [ "derive" ] }

# Substrate
sp-api = { path = "../../../substrate/primitives/api", default-features = false, version = "23.0.0" }
sp-consensus-aura = { path = "../../../substrate/primitives/consensus/aura", default-features = false, version = "0.29.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, version = "28.0.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "12.0.0" }

# Polkadot
polkadot-core-primitives = { path = "../../../polkadot/core-primitives", default-features = false, version = "4.0.0" }
polkadot-primitives = { path = "../../../polkadot/primitives", default-features = false, version = "4.0.0" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"polkadot-core-primitives/std",
	"polkadot-primitives/std",
	"sp-api/std",
	"sp-consensus-aura/std",
	"sp-runtime/std",
	"sp-std/std",
]
