
name: Relay-Forkless-Update-Data
on:
  pull_request:
    branches: [ 'develop' ]
    types: [ opened, reopened, synchronize, ready_for_review, converted_to_draft ]
  workflow_dispatch:

jobs:
  envs:
    name: set envs 
    runs-on: [ self-hosted ]
    outputs:
      relay-runtime-version: ${{ steps.set-versions.outputs.RELAY_RUNTIME_VERSION }}
      parachain-version: ${{ steps.set-versions.outputs.PARACHAIN_VERSION }}
    steps:
      - name: checkout infra
        uses: actions/checkout@v4.1.7
        with:
          repository: 'ReDeFi-Blockchain/redefi-infra'
          path: 'redefi-infra'

      - name: Read .env file
        uses: xom9ikk/dotenv@v2.3.0
        with:
          path: redefi-infra/

      - name: set versions
        id: set-versions
        run: |
          echo "RELAY_RUNTIME_VERSION=${{ env.REDEFI_RELAY_RUNTIME_LATEST_VERSION}}" >> $GITHUB_OUTPUT
          echo "PARACHAIN_VERSION=${{ env.REDEFI_PARACHAIN_LATEST_VERSION}}" >> $GITHUB_OUTPUT

  build:
    needs: [envs]
    name: Trigger running Relay-Forkless-Update-Data workflow
    uses: ReDeFi-Blockchain/redefi-infra/.github/workflows/relay-forkless-update-data.yml@main
    secrets: inherit
    with:
      relay-node-version: ${{ github.ref }}
      relay-runtime-version: ${{ needs.envs.outputs.relay-runtime-version }}
      parachain-version: ${{ needs.envs.outputs.parachain-version }}
