[package]
name = "sc-tracing"
version = "25.0.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors.workspace = true
edition.workspace = true
homepage = "https://substrate.io"
repository.workspace = true
description = "Instrumentation implementation for substrate."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ansi_term = "0.12.1"
atty = "0.2.13"
chrono = "0.4.27"
lazy_static = "1.4.0"
libc = "0.2.121"
log = { version = "0.4.17" }
parking_lot = "0.12.1"
regex = "1.6.0"
rustc-hash = "1.1.0"
serde = "1.0.188"
thiserror = "1.0.48"
tracing = "0.1.29"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.2.25", features = ["parking_lot"] }
sc-client-api = { version = "25.0.0", path = "../api" }
sc-tracing-proc-macro = { version = "10.0.0", path = "proc-macro" }
sp-api = { version = "23.0.0", path = "../../primitives/api" }
sp-blockchain = { version = "25.0.0", path = "../../primitives/blockchain" }
sp-core = { version = "25.0.0", path = "../../primitives/core" }
sp-rpc = { version = "23.0.0", path = "../../primitives/rpc" }
sp-runtime = { version = "28.0.0", path = "../../primitives/runtime" }
sp-tracing = { version = "14.0.0", path = "../../primitives/tracing" }

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "bench"
harness = false
