[package]
name = "sc-executor-common"
version = "0.26.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "A set of common definitions that are needed for defining execution engines."
documentation = "https://docs.rs/sc-executor-common/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
thiserror = "1.0.48"
wasm-instrument = "0.3"
sc-allocator = { version = "20.0.0", path = "../../allocator" }
sp-maybe-compressed-blob = { version = "9.0.0", path = "../../../primitives/maybe-compressed-blob" }
sp-wasm-interface = { version = "18.0.0", path = "../../../primitives/wasm-interface" }

[features]
default = []
